### PR TITLE
move tests outside src

### PR DESCRIPTION
**Pull request by elfjes**
Is there a specific reason reason why the tests are located under `src/`? Would it not make more sense to take them to the root of the repository? At the current location the tests are packaged and distributed through pypi which, while not adding a lot to the wheel size, seems unnecesary to me.

### CODE REVIEW

**Comment by lafrech** [comment]
The reason for this is that those tests are run from apispec tests.

**Comment by elfjes** [comment]
Ah alright, I guess then it makes sense to package these tests

just out of curiosity, where/how are those tests run?

**Comment by lafrech** [comment]
Looks like they were lost (or intentionally dropped by @sloria) in https://github.com/marshmallow-code/apispec/commit/357023d63f2445e63c57dab0810c36dc6a6186c8.

**Comment by elfjes** [comment]
Thanks for finding that :)

That commit message sure makes it look like it was intentional: "NOTE: This removes builds against apispec-webframeworks"

which would mean that the tests no longer need to be packaged?

**Comment by lafrech** [comment]
The test in apispec was meant to let apispec developers realize when they introduce changes that break web frameworks extensions. Dependabot here can only realize that when the new apispec is packaged. It was also introduced as a transition when externalizing web-frameworks plugins.

I suppose @sloria doesn't intend to reintroduce it. So we can remove the tests from the package.

**Comment by sloria** [comment]
Yeah, with Azure Pipelines it was easier to set up periodic jobs (https://github.com/marshmallow-code/apispec-webframeworks/blob/f96faa292a45fd0aa5817ff9b1ea80d525de1f52/azure-pipelines.yml#L7), which sort of obviates running webframeworks tests in apispec.

I'm fine with removing the tests from the package.

**Comment by lafrech** [comment]
Oh, great.

**Pull request merged**
